### ISSUE TITLE
Multiple values inside animation do not support scoping

### ISSUE THREAD

**Issue by Archomeda** [tivac/modular-css#208]
First of all, I've had different results using the API and Browerify methods. Sadly I couldn't get the CLI to output stuff for me, so I don't know what result the CLI gives.

Given:
```css
@keyframes testA {
    0% { opacity: 0; }
    100% { opacity: 1; }
}

@keyframes testB {
    0% { background: white; }
    100% { background: black; }
}

.test {
    animation: testA 10s linear infinite, testB 10s linear infinite;
}
```

Output Browserify:
```css
.mcd990d62b_line {
    animation: testA 10s mcd990d62b_linear infinite, testB 10s linear infinite
}
```

Output API:
```css
.mc003112a2_test {
    animation: mc003112a2_testA 10s linear infinite, testB 10s linear infinite
}
```

I left out the keyframes for brevity.

Both are incorrect. The result I expect:
```css
.mc003112a2_test {
    animation: mc003112a2_testA 10s linear infinite, mc003112a2_testB 10s linear infinite
}
```
if the scope is `mc003112a2` like in the API result.

---

When I leave out `linear` in both animations the results become

Browserify:
```css
.mcd990d62b_line {
    animation: mcd990d62b_testA 10s infinite, testB 10s infinite
}
```

API:
```css
.mc003112a2_test {
    animation: mc003112a2_testA 10s infinite, testB 10s infinite
}
```

which is also incorrect of course.

---

I don't know why or how the results are different depending on which method I use. I'm also unsure if this problem is only with animation, or if this is an issue elsewhere too.

My environment:
- Node: v6.4.0
- OS: Windows 10
- modular-css: v0.28.2
