### ISSUE TITLE
Possible to use selectors from another file?

### ISSUE THREAD

**Issue by chielkunkels** [tivac/modular-css#211]
I was wondering if it's at all possible to somehow get the selector name from another file in order to do something when they're nested within another module?

A bit badly worded perhaps, but let me explain.

For example, I have two files:

#### `field.css`

```css
/**
 * 10px vertical space between field containers
 */
.container {
    margin-top: 10px;
}

```

#### `fieldset.css`

```css
.container {
    display: flex;
}

/**
 * when nested inside a fieldset container, I want
 * each field to have 10px *horizontal* space
 */
.container > <field.container> {
    margin-top: 0;
    margin-left: 10px;
}
```

The problem I'm currently having is that I don't know what the generated selector for the `.container` in `field.css` is, so I've just indicated that here with `<field.container>` - but is this possible at all?

P.S.: only just saw you work at ArenaNet - very cool. I've played waaaay too much GW2.

**Comment by tivac** [comment]
There's a big discussion in CSS Modules (... somewhere) talking about different options here. Since the syntax hasn't really been agreed upon yet I've held off from doing anything around this. It's a little clunky for now, but you can invert things.

```css
/* fieldset.css */
.container {
    composes: field from "./field.css";
    
    margin-top: 0;
    margin-left: 10px;
}
```
