### ISSUE TITLE
Document differences between CSS Modules & modular-css

### ISSUE THREAD

**Issue by tivac** [tivac/modular-css#217]
It's time to actually document what is compatible and what isn't. This is gonna be an adventure.

**Comment by tivac** [comment]
- CSSM on windows has a double-prefixing bug for composition.

```css
/* 1.css */
.red { background: red; }

/* 2.css */
.red { composes: red from "./1.css"; }

/* Output */
{ Error: ENOENT: no such file or directory, open 'C:\C:\Users\pcavit\Desktop\css-modules\1.css'
  errno: -4058,
  code: 'ENOENT',
  syscall: 'open',
  path: 'C:\\C:\\Users\\pcavit\\Desktop\\css-modules\\1.css' }
```

- `modular-css` is always in local scope.
- `modular-css` only supports parenthesized version of `:global(...)`

```css
/* CSS Modules */
:global .one .two { ... }

/* modular-css */
:global(.one .two) { ... }
```

**Comment by TheSisb** [comment]
`modular-css` implements `:external` (https://github.com/tivac/modular-css/blob/master/docs/features.md#overriding-styles)

**Comment by tivac** [comment]
`modular-css` also supports importing an entire module into a [namespace](https://github.com/tivac/modular-css/blob/master/docs/features.md#namespaces).

```css
@value * as layout from "./layout.css";

.content {
    composes: layout.vbox, layout.centered;
}
```
