### ISSUE TITLE
Class not replaced in CSS file with cssnano and an oddly-placed comment

### ISSUE THREAD

**Issue by chrisvasz** [tivac/modular-css#228]
Ok, this is a pretty specific set of conditions, but here we go...

build.js
```js
const browserify = require('browserify');
browserify({ entries: ['./test.js'] })
.plugin('modular-css/browserify', {
  css: 'test.min.css',
  done: [require('cssnano')],
}).bundle().pipe(process.stdout);
```

test.js
```js
const styles = require('./test.css');
```

test.css
```css
.test, /* comment #1 - this comment breaks stuff */
.test:hover {  /* comment #2 - ...but this comment is fine */
  position: absolute;
}

.ok {
  padding: 4px;
}
```

Under those specific conditions, Browserify outputs a JS file with a module that looks like this:
```js
module.exports = {
    "test": "mc003112a2_test",
    "ok": "mc003112a2_ok"
};
```

...but test.min.css looks like this:
```css
.test,.test:hover{position:absolute}.mc003112a2_ok{padding:4px}
```
(notice that the .test class was not replaced correctly even though it appears that a new classname was generated because of the JS output)

I can do two things to make modular-css output a correct CSS file:
1. Remove `require('cssnano')` from the `done` array
2. Remove comment #1 from the original test.css file

I glanced through the modular-css code, but I am unsure how plugins from the `done` array could affect class name resolutions since they appear to happen in different invocations of `postcss`.

This is not a high-priority issue since it has such an easy workaround -- remove the offending comment -- but I wanted to document it here because it bit us in production.
