### ISSUE TITLE
Composition of multiple selectors shouldn't be supported

### ISSUE THREAD

**Issue by tivac** [tivac/modular-css#238]
```css
.base { background: blue; }
.one .two .three { composes: base; }
```

generates

```json
{
    "base": "mc003112a2_base",
    "one": "mc003112a2_base mc003112a2_one",
    "two": "mc003112a2_base mc003112a2_two",
    "three": "mc003112a2_base mc003112a2_three"
}
```

which is complete nonsense & shouldn't be supported.

From the [CSS Modules readme](https://github.com/css-modules/css-modules/#composition)

> Extending works only for local-scoped selectors and only if the selector is a single class name

This will be a **breaking** change 😞
