### ISSUE TITLE
@value references aren't walked during initial processing

### ISSUE THREAD

**Issue by tivac** [tivac/modular-css#24]
```css
@value cssFlex: "../../styles/flex.css";

.vbox {
    composes: vbox from cssFlex;
}
```

This will fail, because during the initial walk of the dependency tree it isn't recognized as a dependency.

To solve this, I think `@value` processing needs to be split into two phases.

1. Update value usage that don't require composition to resolve
2. Update any composed values

The first phase could happen during the initial tree walk and would aid in discovery of issues like this, and then the second phase could happen during the main postcss processing phase later once all the files have been loaded.

We're already parsing each file as we discover it during the walk, so a simple transform instead shouldn't be a big deal.
