### ISSUE TITLE
animation-name: none goes haywire

### ISSUE THREAD

**Issue by tivac** [tivac/modular-css#256]
```css
.one {
    animation-name: none;
}
```

becomes

```css
.mc003112a2_one {
    animation-name: undefinednundefinedoundefinednundefinedeundefined;
}
```

ಠ_ಠ
