### ISSUE TITLE
div:hover :external(...) failing

### ISSUE THREAD

**Issue by tivac** [tivac/modular-css#261]
This should be valid.

```css
// 1.css
.links {
  color: red;
}

// 2.css
thing:hover :external(links from "./1.css") {
  color: blue;
}
```

But is failing for unknown reasons. The error:

```
CssSyntaxError: modular-css-graph-nodes: /2.css:1:1: SyntaxError: Expected "*", identifier, reference, or references but end of input found.

> 1 | thing:hover :external(links from "./1.css") {
    | ^
  2 |   color: blue;
  3 | }
```

http://loud-yak.surge.sh/#!/?state=W3sibmFtZSI6IjEuY3NzIiwiY3NzIjoiLmxpbmtzIHtcbiAgY29sb3I6IHJlZDtcbn0ifSx7Im5hbWUiOiIyLmNzcyIsImNzcyI6InRoaW5nOmhvdmVyIDpleHRlcm5hbChsaW5rcyBmcm9tIFwiLi8xLmNzc1wiKSB7XG4gIGNvbG9yOiBibHVlO1xufSJ9XQ%3D%3D
