### ISSUE TITLE
Support multiple :global pseudo selectors inside single selector

### ISSUE THREAD

**Issue by plesiecki** [tivac/modular-css#277]
Hi,

Currently modular-css doesn't support mutiple `:global` inside single selector.

```css
:global(.foo) :global(.bar) {
  color: red;
}
```

outputs something like this:
```css
.foo :global(.bar_hash123) {
  color: red;
}
```

Expected result looks like this:
```css
.foo .bar {
  color: red;
}
```

[Live example](http://m-css.com/#!/?state=W3sibmFtZSI6IjEuY3NzIiwiY3NzIjoiOmdsb2JhbCguZm9vKSA6Z2xvYmFsKC5iYXIpIHtcblx0Y29sb3I6IHJlZDtcbn0ifV0%3D)

**Comment by tivac** [comment]
Reasonable, combining them does what you'd hope for though.

```css
:global(.foo .bar) {
    color: red;
}

/* outputs */

.foo .bar {
    color: red;
}
```

http://m-css.com/#!/?state=W3sibmFtZSI6IjEuY3NzIiwiY3NzIjoiOmdsb2JhbCguZm9vIC5iYXIpIHtcblx0Y29sb3I6IHJlZDtcbn0ifV0%3D

Taking a look at #278 now.
