### ISSUE TITLE
Empty stylesheet for non-initial builds while watching with rollup

### ISSUE THREAD

**Issue by aktiur** [tivac/modular-css#288]
While configuring watching with Rollup and modular-css, I noticed that while the my style.css is correctly generated on first build, it is always empty for subsequent builds.

Here's my rollup.config.js:
```javascript
import resolve from 'rollup-plugin-node-resolve';
import css from 'modular-css-rollup';

export default {
  entry: 'src/main.js',
  format: 'iife',
  plugins: [
    css({
      css: 'dist/style.css'
    }),
    resolve()
  ],
  dest: 'dist/bundle.js',
  moduleName: 'mymodule'
};
```

Here's where I import a css file:
```javascript
import css from './dashboard.css';

function dashboard(root) {
  const app = root.append('div');

  app.attr('class', css.app)
    .text('Salut la compagnie !');
}

export default dashboard;
```

Here's the css file that is imported:
```css
.app {
    color: red;
}
```

And the resulting bundled `style.css` when first running `rollup -c -w`:
```css
/* src/components/dashboard.css */
.mc26720e23_app {
    color: red
}
/*# sourceMappingURL=data:application/json;base64,eyJ2ZXJzaW9uIjozLCJzb3VyY2VzIjpbIi4uL3NyYy9jb21wb25lbnRzL2Rhc2hib2FyZC5jc3MiXSwibmFtZXMiOltdLCJtYXBwaW5ncyI6IkFBQUEsa0NBQUM7QUFBRDtJQUNJLFVBQVc7Q0FDZCIsImZpbGUiOiJzdHlsZS5jc3MiLCJzb3VyY2VzQ29udGVudCI6WyIuYXBwIHtcbiAgICBjb2xvcjogcmVkO1xufVxuIl19 */
```

And how it looks after changing any file (including the one that imports the CSS file).

```css

/*# sourceMappingURL=data:application/json;base64,eyJ2ZXJzaW9uIjozLCJzb3VyY2VzIjpbXSwibmFtZXMiOltdLCJtYXBwaW5ncyI6IiIsImZpbGUiOiJzdHlsZS5jc3MifQ== */
```

Here are my dev dependencies:
```javascript
  "devDependencies": {
    "eslint": "^3.19.0",
    "modular-css-rollup": "^4.1.7",
    "rollup": "^0.41.6",
    "rollup-plugin-node-resolve": "^3.0.0",
    "rollup-watch": "^3.2.2"
  },
```

I'm not sure what I did wrong!
