### ISSUE TITLE
Tree Shaking does not work

### ISSUE THREAD

**Issue by jantimon** [tivac/modular-css#333]
Hi,

I tried the following with rollup:

index.js
```js
import { fancyClass } from 'test.css';
console.log(fancyClass);
```

test.css
```css
.shakeIt { display: none }
.fancyClass { display: block }
```

Unfortunately the `shakeIt` class is still added to the result css.
