### ISSUE TITLE
Using :external twice in the same selector only transforms the first one

### ISSUE THREAD

**Issue by chielkunkels** [tivac/modular-css#342]
Hey Pat,

Found a small bug with `:external`:

Doing something like
```css
:external(content from './page.css') :external(container from './summary.css') {
	opacity: .5;
}
```
 Comes out as
```css
.mc10fec9bb_content :external(container from './summary.css') {
  opacity: .5;
}
```

If I nest the thing (using `postcss-nested`)
```css
:external(content from './page.css') {
	:external(container from './summary.css') {
		opacity: .5;
	}
}
```
It correctly comes out as
```css
.mc10fec9bb_content .mca9609b55_container {
  opacity: .5;
}
```

Not a huge issue since it's easily worked around, bug figured you might wanna know.

As always, thanks for the amazing package, using it all my projects, at work and personal.

Cheers,
Chiel
