### ISSUE TITLE
When imported vars have names that start the same, they can "collide"

### ISSUE THREAD

**Issue by getkey** [tivac/modular-css#363]
The best way to describe this is an example so [here you go](http://m-css.com/#W3sibmFtZSI6Ii8xLmNzcyIsImNzcyI6IkB2YWx1ZSBzdGVlbGdyZXk6ICM3ZTkxYWI7XG5AdmFsdWUgc3RlZWxncmV5LWxpZ2h0OiAjYmFjOWRlO1xuIn0seyJuYW1lIjoiLzIuY3NzIiwiY3NzIjoiQHZhbHVlICogYXMgdiBmcm9tICcxLmNzcyc7XG5cbi5zdHVmZiB7XG4gIGNvbG9yOiB2LnN0ZWVsZ3JleS1saWdodDtcbn0ifV0=)!

## Files
```css
/* /1.css */
@value steelgrey: #7e91ab;
@value steelgrey-light: #bac9de;
```
```css
/* /2.css */
@value * as v from '1.css';

.stuff {
  color: v.steelgrey-light;
}
```

## CSS Output

```css
/* 2.css */
.mc749ba2db_stuff {
  color: #7e91ab-light;
}
```
