### ISSUE TITLE
Global does not support comma separated classes and/or ID's

### ISSUE THREAD

**Issue by AndrewLeedham** [tivac/modular-css#395]
I am working on implementing `modular-css-rollup 7.20` in to my project which includes Eric Meyer's CSS Reset. The reset includes a lot of grouped styles, I would expect the following to occur:
```css
:global(article, aside, details, figcaption, figure, 
footer, header, hgroup, menu, nav, section) {
	display: block;
}
```
To output:
```css
article, aside, details, figcaption, figure, 
footer, header, hgroup, menu, nav, section {
	display: block;
}
```
But it actually outputs:
```css
article aside details figcaption figure 
footer header hgroup menu nav section {
	display: block;
}
```

Would it be plausible for the above to be implemented? Or would grouping each individual class be the only intended way to achieve this?

Thanks,
Andrew
