### ISSUE TITLE
Style removal is too aggressive

### ISSUE THREAD

**Issue by tivac** [tivac/modular-css#56]
```css
.fooga { composes: booga; }
.fooga:hover { color: red; }
```
Looks like this is getting pruned for some reason.
