### ISSUE TITLE
Problem with `:external` on SASS.

### ISSUE THREAD

**Issue by hemmxwxsoo** [tivac/modular-css#568]
I'm using modular-css with SASS, Webpack. When I use `:external`, sass-loader causes an error.
```javascript
{
    test: /\.scss$/,
    loaders: [
        "@modular-css/webpack/loader",
         'sass-loader'
    ],
},
```
```css
.child {
    width: 100px;
    height: 100px;
    background-color: red;
}
:external(app from "./app.scss"):hover .child { // It works when I disable sass-loader
    background-color: yellow;
}
```

## Expected Behavior
![GIF](https://user-images.githubusercontent.com/25719279/54337111-3b33a580-4671-11e9-91f3-b8f356726658.gif)
I want to make `:external` work with sass-loader.

## Current Behavior
When I run a server with `npm run start`, I got an error like
```
ERROR in ./components/child.scss
Module build failed (from ../node_modules/sass-loader/lib/loader.js):

:external(app from "./app.scss"):hover .child {
                  ^
      Invalid CSS after "...ternal(app from": expected selector, was '"./app.scss"):hover'
      in C:\Users\abc\Desktop\modular-css-with-sass-test\src\components\child.scss (line 8, column 20)
 @ ./components/Child.jsx 25:0-33 42:19-24
 @ ./components/App.jsx
 @ ./index.js
 @ multi ../node_modules/webpack-dev-server/client?http://localhost:8080 ../node_modules/webpack/hot/dev-server.js react-hot-loader/patch webpack-dev-server/client?http://localhost:8080 webpack/hot/only-dev-server ./index.js
```

## Steps to Reproduce (for bugs)

1. `git clone https://github.com/hemmxwxsoo/modular-css-with-sass-test`
2. `cd modular-css-with-sass-test`
3. `npm install`
4. `npm run start`

Webpack config's path : `./configs/webpack/common.js`
components path : `./src/components`

## Your Environment

| Executable | Version |
| ---: | :--- |
| `modular-css`  | 22.2.0 |
| `npm --version`  | 6.4.1 |
| `node --version` | 10.15.1 |

| OS | Version |
| --- | --- |
| Windows 10 | 1809 |
