### ISSUE TITLE
consider alternative syntax for composes

### ISSUE THREAD

**Issue by jquense** [tivac/modular-css#689]
### Feature Use Case

Accept an at-rule `@composes` for doing class composition, which provides a nice parity with users of Tailwindcss, which provides `@apply` for a similar sort of effect.

This is more of a syntax nicety thing, but since the cost of implementing would be minimal, it might be a nice to support.

```css
.foo {
  @composes foo bar
  @composes baz from global
 
  color: red;
}
```

The advantage to this syntax is it better mirrors how other preprocessors generally model composition via mixins, etc. For instance, `@extends` in Sass
