### ISSUE TITLE
Question: why does external compose all the classes into a selector?

### ISSUE THREAD

**Issue by jquense** [tivac/modular-css#727]
Just a general question about the original rationale for having `:external` compose all the clases the references composes and not just the class matching the identifier:

```css
.wooga { color: red; }

.booga {
  composes: wooga;
}

// other file
.b :external(booga from  "./simple.css") {
    background: blue;
}
```
Produces:
```css
.b .wooga.booga {
```
 instead of
```css
.b .booga {
```

The current approach it seems maybe more "correct" somehow, but also leads to selectors whose specificity is hard to reason about (and can change indirectly). Wondering if there were specific practical considerations or if you've seen benefits vs downsides to this  approach?

**Comment by tivac** [comment]
I haven't run into any downsides of the current approach, your suspicion is correct in that including all of the dependencies feels more correct and unsurprising to me. They could change out from underneath you, yes, but that's why `:external()` should be used carefully and sparingly.

Is the current behavior causing issues for you?

**Comment by jquense** [comment]
It's not causing issues in the sense something is broken, but it is leading to confusing css, and more bytes. Specifically we use something like tailwindcss where you can have a lot of classes composed in:

```css
.foo {
  composes: pt-5 pb-6 mx-6 bg-red leading-wide from global;
}
```

you end up with a long selector that isn't necessary. I also see the other side of this which is that `composed` classes aren't really part of the thing you are trying to reference, they are an implementation detail, and having to think about them feels a bit off. In any case it's not actively a problem just something we noticed! Will report back if i find something technically limiting
