### ISSUE TITLE
Hash css custom properties

### ISSUE THREAD

**Issue by jquense** [tivac/modular-css#756]
I'm not sure this is a good idea yet, but I think so? Similar to how keyframe animations are handled except that that you'd also want to export the property name e.g.

```css
.foo {
  --color: red;
}

.baz {
  --color: blue;
}

.bar {
  color: var(--color);
}
```

Which would give you something like:

```css
.foo {
  --mcsa345: red;
}

.baz {
  --mcsa345: blue;
}

.bar {
  color: var(--mcsa345);
}
```
```js
{
  '--color:' '--mcsa345'
}
```

The exports is a bit ugly, but still good to export so that they can be set elsewhere. Perhaps it makes sense to export them as `@value`s? Thoughts? Happy to implement
