### ISSUE TITLE
IE7 * hack is removed

### ISSUE THREAD

**Issue by kevinkace** [tivac/modular-css#76]
This complicates using libs like Pure which make use of this hack.

```css
.pure-u {
    display: inline-block;
    *display: inline; /* IE < 8: fake inline-block */
    zoom: 1;
    letter-spacing: normal;
    word-spacing: normal;
    vertical-align: top;
    text-rendering: auto;
}
```

becomes

```css
.mc003112a2_pure-u {
    display: inline-block;
    display: inline;
    /* IE < 8: fake inline-block */
    zoom: 1;
    letter-spacing: normal;
    word-spacing: normal;
    vertical-align: top;
    text-rendering: auto
}
```
