### ISSUE TITLE
Missing duplicates on class composition list

### ISSUE THREAD

**Issue by jln-pl** [tivac/modular-css#799]
## Expected Behavior

All classes, even with duplicates, are on the composition list.

Example:
I want the red color in `result_with_red` class

* Input
  ```css
  .red {
    color: red;
  }

  .blue {
    color: blue;
  }

  .sth_with_blue {
    composes: blue;
  }

  .sth_with_red {
    composes: red;
  }

  .result_with_red {
      composes: sth_with_red;
      composes: sth_with_blue;
      composes: red;
  }
  ```
* Output
  ```css
  /* CSS OUTPUT */
  /* main.css */
  .mcf250d69f_red {
      color: red;
  }

  .mcf250d69f_blue {
      color: blue;
  }

  /* CLASS COMPOSITIONS */
  /**
  {
      "main.css": {
          "red": [
              "mcf250d69f_red"
          ],
          "blue": [
              "mcf250d69f_blue"
          ],
          "sth_with_blue": [
              "mcf250d69f_blue",
              "mcf250d69f_sth_with_blue"
          ],
          "sth_with_red": [
              "mcf250d69f_red",
              "mcf250d69f_sth_with_red"
          ],
          "result_with_red": [
              "mcf250d69f_red",
              "mcf250d69f_sth_with_red",
              "mcf250d69f_blue",
              "mcf250d69f_sth_with_blue",
              "mcf250d69f_red",               // missing class
              "mcf250d69f_result_with_red"
          ]
      }
  }
  **/
  ```

## Current Behavior
In the same example as above I've got `blue` instead of `red` color. There is no another `red` color class occurance.

* Output
  ```css
  /* CSS OUTPUT */
  /* main.css */
  .mcf250d69f_red {
      color: red;
  }

  .mcf250d69f_blue {
      color: blue;
  }

  /* CLASS COMPOSITIONS */
  /**
  {
      "main.css": {
          "red": [
              "mcf250d69f_red"
          ],
          "blue": [
              "mcf250d69f_blue"
          ],
          "sth_with_blue": [
              "mcf250d69f_blue",
              "mcf250d69f_sth_with_blue"
          ],
          "sth_with_red": [
              "mcf250d69f_red",
              "mcf250d69f_sth_with_red"
          ],
          "result_with_red": [
              "mcf250d69f_red",
              "mcf250d69f_sth_with_red",
              "mcf250d69f_blue",
              "mcf250d69f_sth_with_blue",      // there is no red here, feature or a bug?
              "mcf250d69f_result_with_red"
          ]
      }
  }
  **/
  ```

## Steps to Reproduce (for bugs)
https://m-css.com/repl/#NrBEHoFsEMEsDsB0BjAzq0AaUiBOBTAEwAIBvAHXmOuOQHsAbO3ALmIMIG5KBfSyxACMGAV3xlKNWo2ZthY7vD7wBqAC4ALAPoB3WJq3zxFKjXqQADnVT5Uc0fkXLVBvQY4TT1c1Zt32RE78KkgEqCIMarr62h4mUj7Wtmzq2m6xgZJmdJZJ-qnRBkaKCTm+yQFcvMGgALq1QA

## Your Environment

| Executable | Version |
| ---: | :--- |
| `modular-css`  | latest |
| `npm --version`  | 7.18.1 |
| `node --version` | 16.4.0 |

| OS | Version |
| ---: | :--- |
| macOS Big Sur | 11.6 |

**Comment by tivac** [comment]
IIRC they're put into a `Set`, so the deduping is expected. What's your use case for wanting it repeated?

**Comment by jln-pl** [comment]
I have a css file with atomic classes for utils like margin, padding, color etc. Every other classes is composed from these utils.

```css
.color_black {
  color: #000000;
}

.margin_40 {
  margin: 40px;
}

.margin_0 {
  margin: 0;
}
```

I have an abstraction for bigger `modules` e.g. button or input_group.

```css
.button {
  composes: margin_40, color_black;
}

.input_group {
  composes: margin_0;
}
```

But sometimes I want to override some classes e.g.

```css
.special_button {
  composes: button;
  composes: input_group;
  composes: margin_40;
}
```
