### ISSUE TITLE
Throw when composing within non-class rules

### ISSUE THREAD

**Issue by plesiecki** [tivac/modular-css#918]
### Describe the bug

When composing within rule with a complex selector like `.complex.selector` modular-css throws an error:
`CssSyntaxError: modular-css-composition: (...) Only simple singular selectors may use composition`.

OTOH it doesn't throw for other cases of misuse. 
<details>
<summary>Incorrect use of the composition.</summary>

```css
.fooga { color: red; }

html { composes: fooga; }

.class:focus { composes: fooga; }

.class::after { composes: fooga; }

@media (all) {
    html { composes: fooga; }
}

/* etc. */
```
</details>

I suppose modular-css could throw an error every time a `compose` is incorrectly used.

### Reproduction

https://m-css.com/repl/#NrBEHoDMEsBsFMBMA6AtgYwM6dAGlMpAPZEDmAhgAQDel6RsRATgFyVPwAmA3JQL4AdAHbDhACwAuqWDWGV5dIqgAORTPExtiZct2GCRQ5OljlsLYugCumWUIWKVajVpIU9Qg8OOnzLcpAS8Ex2DvRO6pqU2u76okIAAqhc0FQAFOSwsACUoQqS0nkO8uGqka46Hg4GXkalCAAeyOoI6BLMRY5lLtFuunFCoAC6Q0A

### System Info

```shell
-
```

### Severity

annoyance
