### ISSUE TITLE
Some styles aren't being removed

### ISSUE THREAD

**Issue by tivac** [tivac/modular-css#98]
Looks like the change in #64 was a little too broad, because now this

```css
.wooga { color: red; }
.booga { composes: wooga; }
.booga + .booga { margin: 5px; }
```

isn't having `.fooga` stripped out, even though that's totally fine to do here. At the very least it **definitely** shouldn't still contain a `composes` rule if it's gonna continue to exist.

I should probably have provided more context for #56/#64, because now I don't know why I'd want the original selector to stick around in the pseudo-class version.
